name: GCP Cloud - MQTT Authentication

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
      
  testRSA:
      needs: build
      environment: RSA
    - name: Run GCP Tests
      run: java -jar jar/com.complacentsee.flexyGCPIoT.jar ${{ secrets.PROJECTID }} ${{ secrets.REGION }} ${{ secrets.REGISTRYID }} $DEVICEID $PRIVATEKEYTYPE $PRIVATEKEY

  testECDSA:
      needs: build
      environment: EC
    - name: Run GCP Tests
      run: java -jar jar/com.complacentsee.flexyGCPIoT.jar ${{ secrets.PROJECTID }} ${{ secrets.REGION }} ${{ secrets.REGISTRYID }} $DEVICEID $PRIVATEKEYTYPE $PRIVATEKEY
