name: GCP Cloud - MQTT Authentication

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml

    - name: Upload built jar
      uses: actions/upload-artifact@v2
      with:
        name: builtjar
        path: ./jar
      
  testRSA:
    needs: build
    runs-on: ubuntu-latest
    environment: RSA
    steps:
    - name: Download built jar
      uses: actions/download-artifact@v2
      with:
        name: builtjar
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run GCP Tests
      run: java -jar com.complacentsee.flexyGCPIoT.jar "${{ secrets.PROJECTID }}" "${{ secrets.REGION }}" "${{ secrets.REGISTRYID }}" "${{ secrets.DEVICEID }}" "${{ secrets.PRIVATEKEYTYPE }}" "${{ secrets.PRIVATEKEY }}"

  testECDSA:
    needs: build
    runs-on: ubuntu-latest
    environment: EC
    steps:
    - name: Download built jar
      uses: actions/download-artifact@v2
      with:
        name: builtjar
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run GCP Tests
      run: java -jar com.complacentsee.flexyGCPIoT.jar "${{ secrets.PROJECTID }}" "${{ secrets.REGION }}" "${{ secrets.REGISTRYID }}" "${{ secrets.DEVICEID }}" "${{ secrets.PRIVATEKEYTYPE }}" "${{ secrets.PRIVATEKEY }}"
      
